### ISSUE TITLE
why use bash instead of git aliases?

### ISSUE THREAD

**Issue by phra** [fteem/git-semantic-commits#5]
hi,

it would be better to use ~/.gitconfig (alias section) instead of bash specific files, isn't it?

**Comment by fteem** [comment]
Hey,
sure, you could use Git aliases, but they have their limitations. For example, they won't allow you to have conditional logic like [this](https://github.com/fteem/git-semantic-commits/blob/master/git-chore#L2-L7) if I remember correctly.

**Comment by phra** [comment]
yeah, it's a bit tricky to have conditional logic in aliases but it's possible.
look at [this](http://stackoverflow.com/a/36815667)
maybe we can create a branch with git aliases along with master branch with bash scripts.
what do you think?

**Comment by fteem** [comment]
Sure, feel free to send a PR :)

**Comment by phra** [comment]
ok, if i have spear time i'll do it. ;)
